use_frameworks!


target 'QMEventTextParser-Mac-Example' do
    #platform :osx, 10.10
    pod 'QMEventTextParsing', :path => '../'

end

target 'QMEventTextParsing_Example' do
  platform :ios, 10.0
  pod 'QMEventTextParsing', :path => '../'
end
